apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
type: Opaque
stringData:
  username: grafana
  passphrase: Password@123

---
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
stringData:
  username: kiali
  passphrase: Password@123

---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger
  namespace: istio-system
  labels:
    app: jaeger
type: Opaque
stringData:
  username: jaeger
  passphrase: Password@123