{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway }}
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-virtual-services
  namespace: dev
spec:
  hosts:
  - "*"
  gateways:
  - http-gateway                      # 1
  http:
    - match:
        - uri:
            prefix: /retailitemprice
      route:
        - destination:
            host: retail-item-price
            port:
              number: 8095
    - match:
        - uri:
            prefix: /offerplanning
      route:
        - destination:
            host: offer-planning-service
            port:
              number: 8094
    - match:
        - uri:
            prefix: /retailitem
      route:
        - destination:
            host: retail-item
            port:
              number: 8092
    - match:
        - uri:
            prefix: /offervalidator
      route:
        - destination:
            host: offer-validator
            port:
              number: 8091
    - match:
        - uri:
            prefix: /storecluster
      route:
        - destination:
            host: store-cluster
            port:
              number: 8093
    - match:
        - uri:
            prefix: /storesupplier
      route:
        - destination:
            host: store-supplier
            port:
              number: 8096
    - match:
        - uri:
            prefix: /servicetemplate
      route:
        - destination:
            host: kotlin-service-template
            port:
              number: 8097
{{- end -}}